const initialProducts = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description: "Noise cancelling wireless headphones with 30hr battery",
    price: 199.99,
    category: "electronics",
    image: "https://picsum.photos/300",
  },
  {
    id: 2,
    name: "Organic Cotton T-Shirt",
    description: "100% organic cotton unisex t-shirt",
    price: 29.99,
    category: "clothing",
    image: "https://picsum.photos/301",
  },
  {
    id: 3,
    name: "Organic Cotton Pants",
    description: "100% organic cotton unisex Pants",
    price: 29.99,
    category: "clothing",
    image: "https://picsum.photos/302",
  },
  {
    id: 4,
    name: "Product A",
    image: "https://picsum.photos/303",
    price: "$10",
    category: "electronics",
    description: "This is the product 1",
  },
  {
    id: 5,
    name: "Product B",
    image: "https://picsum.photos/304",
    price: "$20",
    category: "stationary",
    description: "this is the product 2",
  },
  {
    id: 6,
    name: "Product C",
    image: "https://picsum.photos/305",
    price: "$30",
    category: "electronics",
    description: "this is the product 3",
  },
  {
    id: 7,
    name: "Product D",
    image: "https://picsum.photos/306",
    price: "$40",
    category: "stationary",
    description: "this is the product 4",
  },
  {
    id: 8,
    name: "Product E",
    image: "https://picsum.photos/307",
    price: "$50",
    category: "electronics",
    description: "This is the product 5",
  },
];

export default initialProducts;
